parameters:
- name: CanaryMode
  default: false
- name: VariableLocation
  default: ''
- name: Environments
  default: {}
  type: object

jobs:
- template: /CICD/pipeline/jobs/build.yml@self
  parameters:
    CanaryMode: ${{ parameters.CanaryMode }}
    VariableLocation: ${{ parameters.VariableLocation }}
    Environments: ${{ parameters.Environments }}